# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
root = "."
assets_dir = "assets"
bin_dir = "bin"
db_dir = "db"
build_dir = "build"
log_dir = "log"
static_dir = "static"
tmp_dir = "tmp"

[build]
cmd = "go build -o build/workout-of-the-day"
bin = "build/workout-of-the-day"
include_ext = ["go"]
exclude_dir = ["db", "bin", "build", "log", "static", "tmp"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "log/air.log"

[misc]
# Delete tmp directory on exit
clean_on_exit = false
